### ISSUE TITLE
License for the Debian version handling code?

### ISSUE THREAD

**Issue by pombredanne** [amandasaurus/camarabuntu#1]
@rory I stumbled on this post of yours 
- https://www.lucas-nussbaum.net/blog/?p=304#comment-20905 

... with a link to:
- https://repo.or.cz/w/camarabuntu.git?a=blob;f=bin/apt.py;h=f011ac38400bea40213af15a2e49e3d0db25d20f;hb=master (or https://github.com/rory/camarabuntu/blob/60ed5982bbdf7d342e4f3888a8d59e9169036bea/bin/apt.py)

And I would rather like to reuse your code.

What would be your license for this? I may have use for it in my Apache-licensed https://github.com/nexB/scancode-toolkit .
Thank you for your kind consideration.

**Comment by amandasaurus** [comment]
wow this is old! Consider that file under Public Domain (aka CC-zero)

**Comment by pombredanne** [comment]
@rory Thank you ! that oldie but goodie!
